### ISSUE TITLE
re-arrange/re-think the yo questionnaire setup

### ISSUE THREAD

**Issue by mm-paulie** [mediamonks/generator-display-boilerplate#3]
The current setup is quite long and a bit outdated (we never use a single unit for example, we almost always want a plain 300x250)

**Comment by mirkovw** [comment]
Having spoken with @alandawi , the team in BA uses mostly the DC template, whereas we mainly use the 'Plain'. Maybe it makes sense to also add a 'adform' template and push the Flashtalking one to the bottom (don't remove it).

And yes I dont think anyone uses the 'single unit' choice. When you can also choose a single unit in the multi-choice section.. :)
So we can safely get rid of that (and the Vue template along with it. Nobody uses that)

Also can we get rid of the questions about separate HTML/JS/CSS ? In my opinion we should make them shared files by default as this is a nice best practice to follow.

So perhaps we can do something like

Q1: Which unit(s) would you like to create
- choose unit(s) format

Q2: What type?
- choose plain / dc / adform / flashtalking

Other questions:
- Project Name
- Src dir (can we just have this default to ./src/ instead of the weird defaults we get now)

**Comment by mm-paulie** [comment]
Nice, good ideas.

I think it would need to be something with everything defaulted:
What type:
(*)plain
() dc
() adform
() flashtalking

**Comment by alandawi** [comment]
I agree with the ideas, I think it would be useful to make updates on the questions.

Perhaps the only one that seems to me that it is not necessary to change is the html/css/js questions, I consider that it gives you more flexibility when creating the units.

**Comment by mirkovw** [comment]
@mm-paulie yep, having everything defaulted would be great, that we you can quickly navigate through the settings
The vars are a good idea as well. how about adding a -y flag, just like with npm init ? Which will then just create everything with default options

@alandawi yep makes sense, let's keep it then.

**Comment by alandawi** [comment]
I can help with the refactor. I can create a branch from master and start working on this. @mirkovw @mm-paulie are you agree?

**Comment by mirkovw** [comment]
Yes please! Thanks dawi

**Comment by alandawi** [comment]
@mirkovw @mm-paulie 

Updates:

- Delete VueJS template
- Delete createBanner (old code)
- Update questions and clean logic
- Add support to arguments (like _yo display-boilerplate --units "300x600, 300x250" --type plain_) without questions!

https://github.com/alandawi/generator-display-boilerplate/commits/master

Question 1:
Another thing to add to the PR?

Question 2:
Why do we have 3 files (plain.js, doubleclick.js and flashtalking.js) to a very similar code? I think is possible to group into 1 with a few conditionals.

**Comment by mm-paulie** [comment]
Awesome! I will take a loko today.

**Comment by mm-paulie** [comment]
`? What do you want to do? Create display units (you can create multiple or just one)
Error

Cannot read property 'hasArgsUnits' of undefined
`

Getting errors, will check if I can find a solution

**Comment by alandawi** [comment]
@mm-paulie thanks for the comments, I am going to check the errors.

Related to the question1, is if do you have another idea or feature to add, before to create the pull request. Also I will check this new changes on Windows and Mac.

**Comment by alandawi** [comment]
@mm-paulie @mirkovw 

I made some changes and fixed both errors commented above. When you have a free minute, can you do a test in your environment again please?

I did the following tests without problems (using Mac):

- Create quick banner
- Create multi banner
- Create multi banner with separated files
- Create with parameters **yo display-boilerplate --units "300x600, 300x250"**
- Create with parameters **yo display-boilerplate --units "320x320,100x100"**
- Create with parameters **yo display-boilerplate --units "150x150" --type plain**
- Create with parameters **yo display-boilerplate --units "150x150" --type doubleclick**

**Comment by mirkovw** [comment]
this is really great @alandawi !! I will check it out asap

**Comment by alandawi** [comment]
New updates:

- Now is possible to use generate flashtalking banners with parameters
- Bundle the doubleclick/flashtalking/plain files into a generic.js

**Comment by mirkovw** [comment]
@alandawi Just had a look.. nice! I think we're almost there. Just a couple notes/questions

- What is that .yo-rc.json file doing in the root now? Do we need it after de generator is done?
- The default path for source files is ./plain/300x600 or ./doubleclick/300x250. Do we still need them in a subfolder with that name? I usually prefer to have my sourcefiles in ./src/300x600, ./src/728x90 , etc. What do you think?
- I think one of the next big updates is updating all the dependencies so we don't get all those 'deprecated' warnings on install

**Comment by alandawi** [comment]
@mirkovw Thanks for the feedback!

1) That is created because I use global variables when I get the data from the parameters. I will try to remove that file.

2) I think is important because: 
- You can divide the type of the banners.
- Prevents the replacement of a banner. You can have a flat 300x250 banner, if you generate a 300x250 for doubleclick, it will not replace the same previous size, since it will have its own folder.
- Having separate folders can be filtered in the preview (as a prefix), it can be separated not only by size, but also by type.

3) I will check that! Because I removed a few lines without any usage.
